server:
  port: 8081


logging:
  level:
    io.github.resilience4j: DEBUG
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 1  # Set a low limit as the purpose is to queue requests
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      shipmentsServiceRateLimiter:
        limitForPeriod: 1  # Set the actual limit for processing bulk requests
        limitRefreshPeriod: 6s
        timeoutDuration: 5s
        registerHealthIndicator: true
      pricingServiceRateLimiter:
        limitForPeriod: 1
        limitRefreshPeriod: 6s
        timeoutDuration: 5s
        registerHealthIndicator: true
      trackServiceRateLimiter:
        limitForPeriod: 1
        limitRefreshPeriod: 6s
        timeoutDuration: 5s
        registerHealthIndicator: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
    ratelimiter:
      enabled: true
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
