# Server Configuration
server:
  address: localhost
  port: 8081


myapp:
  BASE_URL: http://localhost:8080

# Logging Configuration
logging:
  level:
    io.github.resilience4j: DEBUG


# Resilience4j Rate Limiter Configuration
resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
    instances:
      shipmentsServiceRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 2s
        registerHealthIndicator: true
      pricingServiceRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 2s
        registerHealthIndicator: true
      trackServiceRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 2s
        registerHealthIndicator: true

# Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
    ratelimiter:
      enabled: true
    health:
      show-details: always
